---
- name: Install HAProxy Package
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Ensure HAProxy service is enabled and running
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes

- name: Deploy HAProxy configuration file
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
#    owner: root
#    group: root
#    mode: '0644'
  notify:
    - restart haproxy